/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // Demo of AVLTree usage
        AVLTree tree = new AVLTree();

        // Inserts four nodes into the tree
        tree.insert(3);
        tree.insert(4);
        tree.insert(5);
        tree.insert(6);

        // Prints out a serialized tree (preorder with 'nil' markers)
        System.out.println("Serialized: " + tree.serialize());

        // Deletes a node from the tree
        tree.delete(6);

        // Prints out serialized tree after deletion
        System.out.println("After delete 6: " + tree.serialize());

        // Deserialize into a new tree and serialize again to verify
        String s = tree.serialize();
        AVLTree tree2 = AVLTree.deserialize(s);
        System.out.println("Deserialized: " + tree2.serialize());
    }
}
